In [16]:
import pandas as pd
netflix_dataset = pd.read_csv("netflix_titles.csv")
netflix_dataset.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [17]:
netflix_dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [25]:
## 1. Content Type Distribution

In [24]:
netflix_dataset.value_counts("type",normalize=True) * 100

type
Movie      69.615079
TV Show    30.384921
Name: proportion, dtype: float64

In [26]:
## 2. Top 10 Countries by Content Count

In [28]:
netflix_dataset.value_counts("country").head(10)

country
United States     2818
India              972
United Kingdom     419
Japan              245
South Korea        199
Canada             181
Spain              145
France             124
Mexico             110
Egypt              106
Name: count, dtype: int64

In [29]:
## 3. Analysis of Productions from Turkey

In [37]:
turkey_df = netflix_dataset[netflix_dataset['country'] == 'Turkey']
turkey_df.value_counts("type")

type
Movie      76
TV Show    29
Name: count, dtype: int64

In [38]:
## 4. Most Recent Turkish Productions

In [46]:
turkey_df[["type","title","release_year"]].sort_values("release_year",ascending=False).head(5)

         type        title  release_year
703   TV Show     The Gift          2021
972   TV Show        Fatma          2021
1431    Movie  Stuck Apart          2021
1212    Movie  Paper Lives          2021
1373  TV Show         50M2          2021

In [48]:
## 5. Temporal Analysis: Content Growth Over the Years

In [54]:
netflix_dataset["date_added"] = pd.to_datetime(netflix_dataset["date_added"].str.strip())
netflix_dataset["year_added"] = netflix_dataset["date_added"].dt.year
netflix_dataset["year_added"].value_counts().head(3)

year_added
2019.0    2016
2020.0    1879
2018.0    1649
Name: count, dtype: int64

In [55]:
## 6. Popular Genres and Categories Analysis

In [56]:
netflix_dataset['listed_in'].dropna().str.split(', ').explode().value_counts().head(5)

listed_in
International Movies      2752
Dramas                    2427
Comedies                  1674
International TV Shows    1351
Documentaries              869
Name: count, dtype: int64